# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4d33243b71b163541858ba29611ef4ec636560b5c8ed38a258ad39f43309af594870cc24af23ac81221a988e7e99fe8ee44b99eb06a7f90b4635e78fa0f244

test:
  secret_key_base: 32f50b6f117d5469381f69482df1fcfecc9a6dbf473972ab57b4026925aea6bef663b79326f1e51c701a214a0b9e9a6650386c9c95ec9abb348b250e071b7bfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
